//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace currency.watcher.Properties {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("currency.watcher.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///    &lt;head&gt;
        ///        &lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;https://sinst.fwdcdn.com/css/informers2.css?v=1&quot;&gt;
        ///    &lt;/head&gt;
        ///    &lt;body style=&quot;margin: -18px;&quot;&gt;
        ///        &lt;div id=&quot;SinoptikInformer&quot; style=&quot;width: 160px;&quot; class=&quot;SinoptikInformer type4c1&quot;&gt;
        ///            &lt;div class=&quot;siBody&quot;&gt;
        ///                &lt;div class=&quot;siTitle&quot;&gt;
        ///                    &lt;span id=&quot;siHeader&quot;&gt;&lt;/span&gt;
        ///                &lt;/div&gt;
        ///                &lt;div class=&quot;siCity&quot;&gt;
        ///                    &lt;div class=&quot;siCityName&quot;&gt;
        ///                        &lt;a hre [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string weather {
            get {
                return ResourceManager.GetString("weather", resourceCulture);
            }
        }
    }
}
